AWSTemplateFormatVersion: "2010-09-09"
Description: S3 storage bucket for bound-fastapi

Parameters:
  EnvironmentName:
    Type: String
    Default: production

Resources:
  StorageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${EnvironmentName}-bound-storage
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: CleanupIncompleteUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7

  StorageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StorageBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: EnforceTLS
            Effect: Deny
            Principal: "*"
            Action: s3:*
            Resource:
              - !GetAtt StorageBucket.Arn
              - !Sub ${StorageBucket.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: false

Outputs:
  BucketName:
    Value: !Ref StorageBucket
    Export:
      Name: !Sub ${EnvironmentName}-StorageBucket

  BucketArn:
    Value: !GetAtt StorageBucket.Arn
    Export:
      Name: !Sub ${EnvironmentName}-StorageBucketArn
